<Project>
	<!--net10 sdk下正确编译 net462-->
	<PropertyGroup>
		<RestoreEnablePackagePruning Condition="'$(TargetFramework)' == 'net462' OR '$(TargetFramework)' == 'netstandard2.0'">False</RestoreEnablePackagePruning>
	</PropertyGroup>

	<PropertyGroup Condition="'$(VisualStudioVersion)' >= '18.0' OR $([MSBuild]::VersionGreaterThanOrEquals('$(MSBuildVersion)','18.0'))">
		<OtherTargetFrameworks>net10.0</OtherTargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>
			CS8002;NU1510;SYSLIB5007;CS8603;CS8618;CS1591;CS8625;CS8602;CS8604;CS8600;CS8601;CS8714;CS8619;CS8629;CS8765;CS8634;CS8621;CS8767;CS8633;CS8620;CS8610;CS8631;CS8605;CS8622;CS8613;NU5100;NU5104;NU1903;NU1902;CA1863;CA1812;CA1805;CA1515;CA1508;CA1819;CA1852;CA5394;CA1822;CA1815;CA1813;CA5358;CA5384;CA5400;CA5401;CA1814;CA1835;CA5392;CA5350;CA2100;CA1848;CA1810;CA1513;CA5351;CA1510;CA1512;CA1823;RCS1102;RCS1194;NETSDK1206
		</NoWarn>
		<TouchSocketVersion>4.1.15</TouchSocketVersion>
		<AdminVersion>12.5.5</AdminVersion>
		<FoundationVersion>12.5.7</FoundationVersion>
		<PluginVersion>12.5.8</PluginVersion>
		<ProPluginVersion>12.5.5</ProPluginVersion>
		<GatewayVersion>12.5.7</GatewayVersion>
		<Version>$(GatewayVersion)</Version>

		<ManagementVersion>12.5.2</ManagementVersion>

		
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NET10Version>10.0.5</NET10Version>
		<NET8Version>8.0.25</NET8Version>
		<SatelliteResourceLanguages>zh-Hans;en-US</SatelliteResourceLanguages>

		<!--设置为 true时，删除特定于全球化的代码和数据。 有关详细信息，请参阅固定模式。-->
		<InvariantGlobalization>false</InvariantGlobalization>
	</PropertyGroup>


	<PropertyGroup Condition=" '$(TargetFramework)' != 'net8.0' ">
		<PluginTargetFramework>net10.0</PluginTargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
		<PluginTargetFramework>net8.0</PluginTargetFramework>
	</PropertyGroup>
	
	<PropertyGroup>

		<AnalysisModeDocumentation>All</AnalysisModeDocumentation>
		<AnalysisModeInteroperability>All</AnalysisModeInteroperability>
		<AnalysisModeMaintainability>All</AnalysisModeMaintainability>
		<AnalysisModePerformance>All</AnalysisModePerformance>
		<AnalysisModeSingleFile>All</AnalysisModeSingleFile>
		<AnalysisModeReliability>All</AnalysisModeReliability>
		<AnalysisModeSecurity>All</AnalysisModeSecurity>

	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)Directory.Build.props" Pack="false" PackagePath="\" />
	</ItemGroup>





</Project>
