<Project Sdk="MSTest.Sdk/4.1.0">

	<PropertyGroup>
		<TargetFrameworks>net8.0;$(OtherTargetFrameworks);</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoWarn> CA1812; CA1852;CA1515;$(NoWarn)</NoWarn>
		<IsAotCompatible>false</IsAotCompatible>
		<UseVSTest>true</UseVSTest>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\ThingsGateway.Gateway.Application\ThingsGateway.Gateway.Application.csproj" />
	</ItemGroup>


</Project>
