// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: "autogenerated",dirName: "." }],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;


module.exports = {
  docs: [
    {
      type: "doc",
      id: "description",
      label: "01、说明（使用前必要阅读）"
    },
    {
      type: "doc",
      id: "upgrade",
      label: "02、历史更新"
    },
    {
      type: "category",
      label: "03、支持作者及Pro版",
      items: [
        {
          type: "doc",
          id: "donate",
          label: "3.1 支持作者"
        },
        {
          type: "doc",
          id: "enterprise",
          label: "3.2 Pro版相关"
        },
      ]
    },
    {
      type: "doc",
      id: "startguide",
      label: "04、入门指南",
    },
    {
      type: "category",
      label: "05、网关配置",
      items: [
        {
          type: "doc",
          id: "pluginconfig",
          label: "5.1 插件管理"
        },
        {
          type: "doc",
          id: "plugindebug",
          label: "5.2 驱动调试"
        },
        {
          type: "doc",
          id: "collectdevice",
          label: "5.3 采集设备"
        },
        {
          type: "doc",
          id: "uploaddevice",
          label: "5.4 上传设备"
        },
        {
          type: "doc",
          id: "devicevariable",
          label: "5.5 变量管理"
        },
        {
          type: "doc",
          id: "memoryvariable",
          label: "5.6 中间变量"
        },
        {
          type: "doc",
          id: "otherconfig",
          label: "5.7 其他配置"
        },
      ]
    },
    {
      type: "category",
      label: "06、网关状态",
      items: [
        {
          type: "doc",
          id: "runtimestate",
          label: "6.1 运行状态"
        },
        {
          type: "doc",
          id: "realdata",
          label: "6.2 实时数据"
        },
        {
          type: "doc",
          id: "realalarm",
          label: "6.3 实时报警"
        },
        {
          type: "doc",
          id: "hardwareinfo",
          label: "6.4 硬件信息"
        },
        {
          type: "doc",
          id: "hisdata",
          label: "6.5 历史数据"
        },
        {
          type: "doc",
          id: "hisalarm",
          label: "6.6 历史报警"
        },
      ]
    },
    {
      type: "category",
      label: "07、网关日志",
      items: [
        {
          type: "doc",
          id: "rpclog",
          label: "7.1 RPC日志"
        },
        {
          type: "doc",
          id: "backendlog",
          label: "7.2 后台日志"
        }
      ]
    },
    {
      type: "doc",
      id: "otherpage",
      label: "08、其他页面"
    },
    {
      type: "category",
      label: "09、采集插件",
      items: [
        {
          type: "doc",
          id: "pluginmodbus",
          label: "9.1 Modbus"
        },
        {
          type: "doc",
          id: "pluginopcdaclient",
          label: "9.2 OPCDAClient"
        },
        {
          type: "doc",
          id: "pluginopcuaclient",
          label: "9.3 OPCUAClient"
        },
        {
          type: "doc",
          id: "pluginsiemens",
          label: "9.4 西门子S7"
        },
        {
          type: "doc",
          id: "pluginvigorvs",
          label: "9.5 丰炜VS"
        },
        {
          type: "doc",
          id: "pluginabcip",
          label: "9.6 罗克韦尔CIP"
        },
        {
          type: "doc",
          id: "plugindlt6452007",
          label: "9.7 DLT645_2007"
        },
      ]
    },
    {
      type: "category",
      label: "10、上传插件",
      items: [
        {
          type: "doc",
          id: "pluginopcuaserver",
          label: "10.1 OPCUAServer"
        },
        {
          type: "doc",
          id: "pluginmodbusserver",
          label: "10.2 ModbusServer"
        },

        {
          type: "doc",
          id: "pluginmqttserver",
          label: "10.3 MqttServer"
        },
        {
          type: "doc",
          id: "pluginmqttclient",
          label: "10.4 MqttClient"
        },
        {
          type: "doc",
          id: "pluginrabbitmqclient",
          label: "10.5 RabbitMQ"
        },
        {
          type: "doc",
          id: "pluginkafka",
          label: "10.6 Kafka"
        },
      ]
    },
    {
      type: "category",
      label: "11、部署说明",
      items: [
        {
          type: "doc",
          id: "release",
          label: "11.1 发布"
        },
        {
          type: "doc",
          id: "windowsrelease",
          label: "11.2 Windows部署"
        },
        {
          type: "doc",
          id: "linuxrelease",
          label: "11.3 Linux部署"
        },
      ]
    },
    {
      type: "category",
      label: "12、底层驱动文档",
      items: [
        {
          type: "doc",
          id: "foundation/modbus",
          label: "12.1 Modbus"
        },
        {
          type: "doc",
          id: "foundation/s7",
          label: "12.2 Siemens S7"
        },
        {
          type: "doc",
          id: "foundation/opcda",
          label: "12.3 OPCDAClient"
        },
        {
          type: "doc",
          id: "foundation/opcua",
          label: "12.4 OPCUAClient"
        }
      ]
    },
    {
      type: "link",
      label: "案例合集",
      href: "https://www.cnblogs.com/ThingsGateway/collections/1104"
    },
  ]
};

