<Project Sdk="Microsoft.NET.Sdk.Web">


	<ItemGroup>
		<ProjectReference Include="..\ThingsGateway.Gateway.Razor\ThingsGateway.Gateway.Razor.csproj" />
	</ItemGroup>


	<!--nuget包解压复制文件，上下文动态加载-->
	<Import Project="targets\PluginContext.targets" Condition=" ! $([System.String]::Copy('$(SolutionName)').StartsWith('ThingsGatewayAll'))" />

	<!--nuget包解压复制文件，上下文动态加载，Pro插件-->
	<Import Project="targets\Pro2.targets" Condition=" '$(SolutionName)' != 'ThingsGatewayAll'  OR '$(Configuration)' == 'Release' " />


	<!--nuget包解压复制文件，上下文动态加载-->
	<Import Project="targets\PluginDebug.targets" Condition=" $([System.String]::Copy('$(SolutionName)').StartsWith('ThingsGatewayAll'))" />

	<!--nuget包解压复制文件，上下文动态加载，Pro插件-->
	<Import Project="targets\ProPluginDebug.targets" Condition=" '$(SolutionName)' == 'ThingsGatewayAll'  AND '$(Configuration)' != 'Release' " />
	
	<!--<Import Project="targets\Pro8.targets" />-->

	<!--打包复制-->
	<Import Project="targets\PluginPublish.targets" />
	
	<PropertyGroup>

		<GenerateDocumentationFile>false</GenerateDocumentationFile>

		<TargetFrameworks>net8.0;$(OtherTargetFrameworks);</TargetFrameworks>
		<CustomTargetFramework>$(TargetFramework)</CustomTargetFramework>
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
		<SatelliteResourceLanguages>zh-Hans;en-US</SatelliteResourceLanguages>
		<PublishReadyToRunComposite>true</PublishReadyToRunComposite>
		<ApplicationIcon>favicon.ico</ApplicationIcon>

		<CETCompat>false</CETCompat>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<!--动态适用GC-->
		<GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>

	</PropertyGroup>



	<ItemGroup>
		<Content Update="wwwroot\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


	<ItemGroup>
		<Content Remove="Locales\*.json" />
		<EmbeddedResource Include="Locales\*.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>


	<ItemGroup>
		<None Include="Layout\BlazorApp.razor" />
		<None Include="Layout\BlazorAppNet8.razor" />
	</ItemGroup>


	
	<!--安装服务守护-->
	<ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">

		<PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
		<Content Remove="Layout\BlazorApp.razor" />
		<Content Update="Layout\BlazorAppNet8.razor" />
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
		<PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="$(NET10Version)" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="$(NET10Version)" />
		<Content Remove="Layout\BlazorAppNet8.razor" />
		<Content Update="Layout\BlazorApp.razor" />
	</ItemGroup>


	<ItemGroup>
		<Content Include="Dockerfile">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="MinimumCompatibleVersion">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Dockerfile_arm64">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="DockerPush.ps1">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="DockerPush_arm64.ps1">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="favicon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<None Update="ThingsGateway.pfx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="pm2-windows.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="pm2-linux.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="thingsgateway.service">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="WindowsWebDisable.bat">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="WindowsServiceCreate.bat">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="WindowsServiceDelete.bat">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

	</ItemGroup>



</Project>
