/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "thingsgateway",
  "tagline": "物联网",
  "url": "https://diego2098.gitee.io",
  "baseUrl": "/thingsgateway-docs/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "projectName": "ThingsGateway",
  "scripts": [],
  "themeConfig": {
    "zoom": {
      "selector": ".markdown :not(em) > img,.markdown > img, article img[loading]",
      "background": {
        "light": "rgb(255, 255, 255)",
        "dark": "rgb(50, 50, 50)"
      },
      "config": {}
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "prism": {
      "additionalLanguages": [
        "powershell",
        "csharp",
        "sql"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "navbar": {
      "title": "ThingsGateway",
      "logo": {
        "alt": "ThingsGateway Logo",
        "src": "img/ThingsGatewayLogo.png"
      },
      "hideOnScroll": true,
      "items": [
        {
          "to": "docs",
          "activeBasePath": "docs",
          "label": "文档",
          "position": "left"
        },
        {
          "label": "更新日志",
          "position": "left",
          "to": "docs/upgrade"
        },
        {
          "label": "源码",
          "position": "right",
          "items": [
            {
              "label": "Gitee（主库）",
              "href": "https://gitee.com/diego2098/ThingsGateway"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/kimdiego2098/ThingsGateway"
            },
            {
              "label": "Nuget",
              "href": "https://www.nuget.org/profiles/kimdiego"
            }
          ]
        },
        {
          "label": "社区",
          "position": "right",
          "href": "https://gitee.com/dotnetchina"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "文档",
          "items": [
            {
              "label": "入门",
              "to": "docs"
            },
            {
              "label": "手册",
              "to": "docs"
            }
          ]
        },
        {
          "title": "社区",
          "items": [
            {
              "label": "讨论",
              "href": "https://gitee.com/diego2098/ThingsGateway/issues"
            },
            {
              "label": "看板",
              "href": "https://gitee.com/diego2098/ThingsGateway/board"
            }
          ]
        },
        {
          "title": "更多",
          "items": [
            {
              "label": "仓库",
              "href": "https://gitee.com/diego2098/ThingsGateway"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2020-2023 Diego."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "E:\\Tg\\ThingsGateway\\NewThingsGateway\\handbook\\sidebars.js",
          "editUrl": "https://gitee.com/diego2098/ThingsGateway/tree/master/handbook/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true,
          "sidebarCollapsible": true,
          "sidebarCollapsed": true
        },
        "theme": {
          "customCss": "E:\\Tg\\ThingsGateway\\NewThingsGateway\\handbook\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "plugins": [
    "E:\\Tg\\ThingsGateway\\NewThingsGateway\\handbook\\node_modules\\docusaurus-plugin-image-zoom\\src\\index.js"
  ],
  "themes": [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "language": [
          "en",
          "zh"
        ],
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
